### Posts API
# Add a New Post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "My First Post",
    "content": "This is the content of my first post.",
    "sender": "User123"
}

###
# Get All Posts
GET http://localhost:3000/posts

###
# Get Post by ID
GET http://localhost:3000/posts/<post_id>

###
# Get Posts by Sender
GET http://localhost:3000/posts?sender=<sender_id>

###
# Update a Post
PUT http://localhost:3000/post/<post_id>
Content-Type: application/json

{
    "title": "Updated Post Title",
    "content": "This is the updated content.",
    "sender": "User123"
}

###
# Add New Comment
POST http://localhost:3000/comments
Content-Type: application/json

{
    "postId": "<post_id>",
    "content": "This is a comment on the post."
}

###
# Get All Comments
GET http://localhost:3000/comments

###
# Get Comment by Comment ID
GET http://localhost:3000/comments/<comment_id>

###
# Get Comments by Post ID
GET http://localhost:3000/comments/byPostId/<post_id>

###
# Update Comment by ID
PUT http://localhost:3000/comments/<comment_id>
Content-Type: application/json

{
    "content": "Updated comment content."
}

###
# Delete Comment by ID
DELETE http://localhost:3000/comments/<comment_id>